#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="/Users/ben/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH=$PATH:/Users/ben/Software/activator-1.3.2-minimal
export ANDROID_HOME=/usr/local/opt/android-sdk

alias a="atom ."
alias sc="steroids connect"
alias sd="steroids deploy"

setopt AUTO_CD

setopt RM_STAR_WAIT

###-tns-completion-start-###
if [ -f /Users/ben/.tnsrc ]; then
    source /Users/ben/.tnsrc
fi
###-tns-completion-end-###
